// Code generated by MockGen. DO NOT EDIT.
// Source: ./mongo/mongo_monitor.go
//
// Generated by this command:
//
//	mockgen -source ./mongo/mongo_monitor.go -destination ./tests/mock/mongo/mongo_monitor.go
//

// Package mock_mongo is a generated GoMock package.
package mock_mongo
