name: "PR: Test"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run Go Test
        id: test
        run: make run-tests-report
